<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload Logo</name>
   <tag></tag>
   <elementGuidId>25cf05e1-444b-45f0-a9fe-11b3cddf0653</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Upload Logo' or . = 'Upload Logo')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:rk:']/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45ca9415-1908-4fe4-9b05-9142f81e570a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn min-h-12 h-12 text-[16px] font-semibold btn-primary btn-outline !hover:text-white</value>
      <webElementGuid>e6301c8a-b7cf-417c-bc54-0017dc55afd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload Logo</value>
      <webElementGuid>8cb76d4a-57c8-43f5-bc72-25c50ebe91a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rk:&quot;)/div[@class=&quot;flex w-full flex-col px-4 pb-4&quot;]/div[@class=&quot;flex flex-row pt-4 gap-4&quot;]/div[@class=&quot;flex flex-col items-start justify-center hover:text-white&quot;]/button[@class=&quot;btn min-h-12 h-12 text-[16px] font-semibold btn-primary btn-outline !hover:text-white&quot;]</value>
      <webElementGuid>bd014380-a5f2-480c-9956-35eebc0b9eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rk:']/div[2]/div/div/button</value>
      <webElementGuid>d88b0825-1112-4317-b9bb-2e808fd0ae87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Logo'])[1]/following::button[1]</value>
      <webElementGuid>36181cd0-d12d-4d5f-84ff-e83509554384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Name'])[1]/following::button[1]</value>
      <webElementGuid>aaf178d2-23d5-4202-9c6a-33d59b00140b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>e5ce5810-2625-4517-9579-534c9a2698aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[2]</value>
      <webElementGuid>b9d78055-a46a-452e-bcca-f0b73f04c6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload Logo']/parent::*</value>
      <webElementGuid>eb174396-c0e2-4fcb-88c9-afba01dd39a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>7e337b16-830d-4bef-9bf4-cc0580358b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Upload Logo' or . = 'Upload Logo')]</value>
      <webElementGuid>bb75de45-b3f0-4a97-aaee-ac68d599bc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:ri:']/div[2]/div/div/button</value>
      <webElementGuid>879b986c-c40d-4848-8b26-e48ce9681f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rf:']/div[2]/div/div/button</value>
      <webElementGuid>4a2855b9-0f08-4640-92b6-83ec55f8f2bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
