<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Brand</name>
   <tag></tag>
   <elementGuidId>9b1fb170-c97c-49e5-b848-67bb8a56d6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand &amp; Branch'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>958af52c-6621-4d55-a771-472a49df74b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-600 hover:text-primary</value>
      <webElementGuid>5e7ef4a8-287f-42ad-84f1-dc642c65ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brand</value>
      <webElementGuid>c7ceb1f1-62c4-4aff-8079-75af4088bc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_8033ae&quot;]/div[@class=&quot;w-full text-black dark:text-light&quot;]/div[@class=&quot;flex min-h-[100vh]&quot;]/div[@class=&quot;sticky left-0 top-0 z-[50] bg-white shadow-md&quot;]/div[@class=&quot;w-[220px]  sticky top-0 z-[50] bg-white transition-all duration-300&quot;]/div[@class=&quot;sticky top-0 h-[calc(100vh-50px)] overflow-y-auto m-0 min-w-full list-none p-0&quot;]/div[@class=&quot;menu-item-wrapper&quot;]/div[@class=&quot;pl-[60px] text-b5&quot;]/ul[@class=&quot;m-0 list-none p-0&quot;]/li[@class=&quot;py-2 text-gray-600&quot;]/a[1]/div[@class=&quot;text-gray-600 hover:text-primary&quot;]</value>
      <webElementGuid>401fd63f-1aed-4b43-be26-4649dc8c55be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand &amp; Branch'])[1]/following::div[3]</value>
      <webElementGuid>2fc0663a-2648-464d-a77f-62b6ddd488b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[1]/following::div[7]</value>
      <webElementGuid>f8af3ca1-e40f-4061-915a-4e1f8596c9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/preceding::div[1]</value>
      <webElementGuid>a60781eb-33c4-41b2-8f59-05e9da3a15c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/preceding::div[3]</value>
      <webElementGuid>b1524b62-4bd3-4ce5-8a0e-f04b0c0fc4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brand']/parent::*</value>
      <webElementGuid>f475d3aa-5033-4f0f-a58f-0184b695b30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/div</value>
      <webElementGuid>71960552-afea-4ea2-97ba-98106ec73e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Brand' or . = 'Brand')]</value>
      <webElementGuid>063f192d-3c6f-45da-bbc8-a8c8afe6746b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
