<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UploadFile</name>
   <tag></tag>
   <elementGuidId>3670cd57-a332-4e55-ab85-da390971c809</elementGuidId>
   <imagePath>C:\Users\NUC\Downloads\ChatGPT.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\NUC\Downloads\ChatGPT.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
