<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand Name_input input-bordered h-42p_d0de7f_1</name>
   <tag></tag>
   <elementGuidId>c7c1705f-a3c8-4672-b2e6-3379a51d437c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dcc65d9-5818-4075-bdb3-03f6f312e356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-bordered h-[42px] w-full border-gray-30 text-b2 !-outline-offset-1 border-gray-300 rounded-xl text-sm placeholder-gray-500 mt-[10px] flex-auto  focus:!border-primary focus:!outline-none focus:!ring-primary</value>
      <webElementGuid>aae6b1a1-6370-49e1-829b-ea32641c91da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input brand name</value>
      <webElementGuid>96299778-3359-4b41-8c12-ea51f5b1e738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c32f964d-d1a6-4eed-8dfd-dc87ed45d0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83ac857d-01d1-47f6-abde-55a3d1873cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>80de88af-310f-4821-8f9f-4b0f9acb9f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rm:&quot;)/div[@class=&quot;flex w-full flex-col p-4 relative&quot;]/input[@class=&quot;input input-bordered h-[42px] w-full border-gray-30 text-b2 !-outline-offset-1 border-gray-300 rounded-xl text-sm placeholder-gray-500 mt-[10px] flex-auto  focus:!border-primary focus:!outline-none focus:!ring-primary&quot;]</value>
      <webElementGuid>a462997e-122d-4806-be7b-89eb54331c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='q']</value>
      <webElementGuid>cfb5dbe0-6a3b-4eef-98dd-6b3f815934c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rm:']/div/input</value>
      <webElementGuid>180601a4-5d80-48c8-ba39-b9d2e691825f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f890b8e8-ec4c-4408-b394-2fcb6316f69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input brand name' and @type = 'text']</value>
      <webElementGuid>f89b60e4-1ddb-4314-8cf6-4b8e39a4925c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
