<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>fef33a71-206b-4aa5-838b-e80e2858b2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:rf:']/div[10]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1534046e-155a-49ad-902d-fb744fc20a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow inline-flex justify-center text-center py-2 border-cream-1000  text-sm hover:border-[#d67a60] hover:text-[##d67a60] 
                                hover:bg-[#d67a60] bg-[#EC9476] text-white rounded-[0.75rem]</value>
      <webElementGuid>d476fb8b-bd30-487a-a472-62067d53b2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add </value>
      <webElementGuid>ae5dba78-117e-4b18-b90d-ee251e50b827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rf:&quot;)/div[@class=&quot;w-full flex p-4 space-x-2&quot;]/button[@class=&quot;flex-grow inline-flex justify-center text-center py-2 border-cream-1000  text-sm hover:border-[#d67a60] hover:text-[##d67a60] 
                                hover:bg-[#d67a60] bg-[#EC9476] text-white rounded-[0.75rem]&quot;]</value>
      <webElementGuid>2060d44a-4783-4837-b643-47cd01600e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rf:']/div[10]/button[2]</value>
      <webElementGuid>bb7d8931-34d4-44eb-bcd5-688ae341e789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>0965ef78-3971-4c48-9ffc-751018c8c868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noted'])[1]/following::button[2]</value>
      <webElementGuid>99aea077-2ca8-4fc3-9d41-fa19be631319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>a055ad2c-18a8-4732-9341-e0ae308e4aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button[2]</value>
      <webElementGuid>43ea946c-f25a-4687-8dad-1dbbe95287a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add ' or . = 'Add ')]</value>
      <webElementGuid>5e9e6d14-5f8d-4053-9782-c3440f755b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
