<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add SupplierSupplier DetailSupplier ID _1e52cd</name>
   <tag></tag>
   <elementGuidId>62b60630-696e-43d2-8feb-fc04e33b3d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:ri:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10fca56b-f46c-4dc2-9598-384d6eb9ac56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto w-1/2 min-w-[70%] lg:min-w-[60%] rounded bg-white mt-10 p-[25px]</value>
      <webElementGuid>f3e02df6-1818-4515-b203-bd3ca4ab352f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-dialog-panel-:ri:</value>
      <webElementGuid>2c000eda-fb71-42e4-b226-0778294d0982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>741dc73d-652e-453c-ab4d-054a5e08fd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add SupplierSupplier DetailSupplier ID   *Tax IDCompany Name  *VatIncludeExcludeGroupSelect Group SupplierchathaiKFC01Daryqueen1tee noichester Uniqlo3214567898798789789Credit TermSupplier ContactNameTel.This value must be no more than 10EmailAddressNotedCancelAdd </value>
      <webElementGuid>9ca8fff2-93ea-4f5c-81f1-fc84f06ae00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:ri:&quot;)</value>
      <webElementGuid>81aa0054-0d38-457c-ad6e-741aabac0a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:ri:']</value>
      <webElementGuid>131901e2-bc10-49f1-8aa6-b556b64ec6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-:r2:']/div[2]/div/div</value>
      <webElementGuid>bfdf6750-bb15-49a6-a44d-e7f2f89535be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'headlessui-dialog-panel-:ri:', '&quot;', ')')])[1]/following::div[8]</value>
      <webElementGuid>bef70ecc-2bcc-4ec1-b1cd-a04026d642f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div</value>
      <webElementGuid>75066117-c156-4cf1-9b13-dc2ea7ff2ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-dialog-panel-:ri:' and (text() = 'Add SupplierSupplier DetailSupplier ID   *Tax IDCompany Name  *VatIncludeExcludeGroupSelect Group SupplierchathaiKFC01Daryqueen1tee noichester Uniqlo3214567898798789789Credit TermSupplier ContactNameTel.This value must be no more than 10EmailAddressNotedCancelAdd ' or . = 'Add SupplierSupplier DetailSupplier ID   *Tax IDCompany Name  *VatIncludeExcludeGroupSelect Group SupplierchathaiKFC01Daryqueen1tee noichester Uniqlo3214567898798789789Credit TermSupplier ContactNameTel.This value must be no more than 10EmailAddressNotedCancelAdd ')]</value>
      <webElementGuid>9a80c9dd-3c52-43a2-a1f0-9749028ea3e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
