<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Category_input-group-1</name>
   <tag></tag>
   <elementGuidId>906524b2-4978-4024-80bf-6bbb31b8ce6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-group-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-group-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb3f3fbd-0a72-4201-8be7-4877c652a2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-group-1</value>
      <webElementGuid>2e44ddbb-1d33-451f-9b3a-1c3c7c60c833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-cream-1000 focus:border-cream-1000 block pl-10 py-2  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500</value>
      <webElementGuid>6fa4bdd6-f735-42f1-a75b-628aa53ef042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>97214806-9e3c-415b-815c-0d76c09bf220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1052adf9-0787-4065-90ca-456d2f6f2c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-group-1&quot;)</value>
      <webElementGuid>c72f2a2f-620f-4f3e-b99f-12190021aae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-group-1']</value>
      <webElementGuid>b5ac7cc8-2e59-4f8c-9017-b0ed52d1a7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:R3qllllaqla:']/div/div/div/input</value>
      <webElementGuid>77946f6b-878e-4b6a-82ad-f55305efe9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0db3e298-8f1a-451d-9c16-33e48db7c68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-group-1' and @placeholder = 'Search...' and @type = 'text']</value>
      <webElementGuid>22070858-c0b5-4b24-a062-ac3935949843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
