<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_UsernamePasswordSign in with Credentia_eb24e8</name>
   <tag></tag>
   <elementGuidId>27688ef0-a1ae-4066-bd2c-029cf62327fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body.__next-auth-theme-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>bf017aaf-b7e1-4e46-af9e-c78f08262864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__next-auth-theme-auto</value>
      <webElementGuid>eb96d003-7292-40b1-b983-17659ad7e943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernamePasswordSign in with Credentialsid(&quot;input-username-for-credentials-provider&quot;)</value>
      <webElementGuid>77dbd72d-04a0-4283-aa6b-201e2eba975d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__next-auth-theme-auto&quot;]</value>
      <webElementGuid>32ced59e-57ec-4b59-b475-17c67276bf1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>a9b28c9a-8dd3-44e0-a1c4-c9357def3329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'UsernamePasswordSign in with Credentialsid(&quot;input-username-for-credentials-provider&quot;)' or . = 'UsernamePasswordSign in with Credentialsid(&quot;input-username-for-credentials-provider&quot;)')]</value>
      <webElementGuid>0151b365-bead-4df4-9dd4-9e614342a846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
