<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_UsernamePasswordSign in with Credentials</name>
   <tag></tag>
   <elementGuidId>5357e08d-4275-432b-a2b6-160bd78b00b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>14498a48-4b41-4957-8764-4e67b5afb8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials</value>
      <webElementGuid>f38a02d2-cb19-4fe8-8d84-67175e68d609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>c186b77b-4f25-4c99-a864-a03668f5b4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernamePasswordSign in with Credentials</value>
      <webElementGuid>4543cace-fc5d-4fa2-a6f7-e2ddc8286667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__next-auth-theme-auto&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;signin&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;provider&quot;]/form[1]</value>
      <webElementGuid>6eea8048-6ec6-420c-bf31-75f6338f97cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials']</value>
      <webElementGuid>96086d15-27e6-49d1-afb8-9de16930a680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>e0b4f840-7fc7-4a15-b9d2-e0eadbd8b9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'UsernamePasswordSign in with Credentials' or . = 'UsernamePasswordSign in with Credentials')]</value>
      <webElementGuid>96c7201b-522d-41fe-a5eb-069365ca87ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
