<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_UsernamePasswordSign in with Credentials</name>
   <tag></tag>
   <elementGuidId>5357e08d-4275-432b-a2b6-160bd78b00b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>66063f7f-c5a8-421b-9b36-683343d9d6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials</value>
      <webElementGuid>22960ebd-ee62-4750-9d5d-8eee32a6184f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>72f245e9-5448-4b32-92df-96528bbc43bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernamePasswordSign in with Credentials</value>
      <webElementGuid>6a38de2d-b040-4dfa-b5c8-fe0992fa5d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__next-auth-theme-auto&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;signin&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;provider&quot;]/form[1]</value>
      <webElementGuid>2a97dcd1-e19b-4a84-b38a-2dac6f81f07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='https://pos-frontend-ton-gumbjqoyzq-as.a.run.app/api/auth/callback/credentials']</value>
      <webElementGuid>6fb4ba79-7fb8-42b6-a596-44ac49217d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>af685880-c647-433e-8454-254717ced7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'UsernamePasswordSign in with Credentials' or . = 'UsernamePasswordSign in with Credentials')]</value>
      <webElementGuid>cac7ac0b-3285-4386-ad55-88f228424623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
