<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>e657bc6e-ee49-4e6b-85e3-59d6579e4f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-username-for-credentials-provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-username-for-credentials-provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c754796-8e7a-4322-92e1-60ffa26b2829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>403ba414-8306-4dfd-a34a-5cb7177974de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-username-for-credentials-provider</value>
      <webElementGuid>886a0c15-18a3-4597-b817-761a831e657e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c941458-cbbd-4906-af29-e567cb9f2f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>jsmith</value>
      <webElementGuid>f6a3c842-3c8c-48e1-9e54-1c6fbfb17680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>813e4793-e5e7-4a9a-887e-0aa69c59f883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-username-for-credentials-provider&quot;)</value>
      <webElementGuid>164a1a30-43cc-4a90-b980-8c24e9da8938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-username-for-credentials-provider']</value>
      <webElementGuid>95f62a8d-6652-40a6-9ba6-3113b66f5b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>99f650c3-1666-48fc-bd16-8aea69ecf239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'input-username-for-credentials-provider' and @type = 'text' and @placeholder = 'jsmith']</value>
      <webElementGuid>3975519b-506d-4b49-a5f7-969cb3a0efcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
