<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>f7720574-52a1-4014-9c7b-e54ad68fb9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-password-for-credentials-provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-password-for-credentials-provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb38857f-6f5f-42f8-b76c-c724d1a4b09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4df28204-066b-4858-913e-f8ce27e5e854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-password-for-credentials-provider</value>
      <webElementGuid>b755b268-f810-4f7e-ba0c-cc77cb3f1da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dccfc2cc-a4b3-4f0e-9419-18149973aeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>927be5a7-beb1-4324-b12b-be4c6b3ea4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-password-for-credentials-provider&quot;)</value>
      <webElementGuid>d5e52dd6-38cf-4e21-88e5-1b456f4aa643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-password-for-credentials-provider']</value>
      <webElementGuid>190cedc6-f1c8-48bc-a93c-10fc33054637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9a3865c0-d8c8-4f31-b100-c09dab2497c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'input-password-for-credentials-provider' and @type = 'password']</value>
      <webElementGuid>d261fbf5-3fc4-4a60-aad6-0297ba395897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
