<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username (2)</name>
   <tag></tag>
   <elementGuidId>93f0e13f-db5b-41e7-adb5-fe16ff82c5cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-username-for-credentials-provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-username-for-credentials-provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ae079be-ef61-4017-897c-7286d04c2d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>7a770810-5cba-44f9-a783-1392a2ff86f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-username-for-credentials-provider</value>
      <webElementGuid>cfb06789-6a7c-4adf-b075-9cff8d40e0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47c6333f-654f-4633-8b41-d3aa3af2b671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>jsmith</value>
      <webElementGuid>fb7b5941-5b9c-434e-9077-da7cb7f56b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>404f6867-ae8b-4070-99f7-e94385c1898f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-username-for-credentials-provider&quot;)</value>
      <webElementGuid>e937d830-1894-49c3-80d2-feabfb4219da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-username-for-credentials-provider']</value>
      <webElementGuid>e905f1cf-058a-41aa-9ad9-8bd4ff3cf5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ea4b77bb-d64d-4e10-991d-590ad11fb9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'input-username-for-credentials-provider' and @type = 'text' and @placeholder = 'jsmith']</value>
      <webElementGuid>6c2f83fa-b26c-4318-9b9c-f54cb0231687</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
