<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username (1)</name>
   <tag></tag>
   <elementGuidId>cfadd7a8-0ff5-4a66-abd4-624b76320e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-username-for-credentials-provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-username-for-credentials-provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f2b572d-6b76-4a7f-93b1-93a9486d9c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>f0e49630-c3dc-41be-a708-609b4be8f5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-username-for-credentials-provider</value>
      <webElementGuid>cdbc243d-5b20-4fe7-8869-5d99c3b89796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb2f63c5-c3bd-4dd0-a794-06c101a16b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>jsmith</value>
      <webElementGuid>57901fac-07ce-42f5-8a86-7cd498535064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>7f4bd497-75e8-4acb-b915-cf8271ae4c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-username-for-credentials-provider&quot;)</value>
      <webElementGuid>e60abc04-e54a-4fb7-94d4-23b09a9881fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-username-for-credentials-provider']</value>
      <webElementGuid>2af79d2a-a739-48f6-bc0b-ab7d548ceb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d3ea179a-5642-4b37-b39c-eb1774c5f088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'input-username-for-credentials-provider' and @type = 'text' and @placeholder = 'jsmith']</value>
      <webElementGuid>a960fd41-b908-47c3-b11e-1f180910c04f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
