<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sub Category_1</name>
   <tag></tag>
   <elementGuidId>054af60c-232e-4fcc-99cd-77ad2c54311e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-tabs-tab-:Riqllllaqla:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b3f2952-d51f-45ba-9f45-6c15edff13de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-24 focus:outline-none border-b-4 text-black border-gray-50 hover:text-[#EC9476] text-sm</value>
      <webElementGuid>622f0306-20e5-4efb-863d-dda7d31d8bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:Riqllllaqla:</value>
      <webElementGuid>131b1343-f2d7-4cde-8053-b3a2d15f8352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fb39cf4f-b953-4488-8154-a9c0c34cf05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2373d263-bc08-4c59-b933-799a3b1dd97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b616a58-ce75-4d3c-b089-67d0b5142095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba86cf50-65e9-4878-ade4-09b59cc75a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-tabs-panel-:R5qllllaqla:</value>
      <webElementGuid>f5af3e06-6d64-400d-85a0-b73cfbe0e060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sub Category</value>
      <webElementGuid>35f9654b-93db-4c75-bd0e-0ef8e9c6858a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:Riqllllaqla:&quot;)</value>
      <webElementGuid>814bdc82-7e21-4832-ab92-349938c23c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-tabs-tab-:Riqllllaqla:']</value>
      <webElementGuid>32f88ebe-df79-406e-a485-734da91e4c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[2]/following::button[1]</value>
      <webElementGuid>d19628ae-5315-4dc3-9453-002a3e0f5a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category List'])[1]/following::button[2]</value>
      <webElementGuid>274e04f8-5f43-4d50-843a-94f3559f6ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Category'])[1]/preceding::button[1]</value>
      <webElementGuid>49d1657a-9def-429c-b9c0-af5566824042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORY'])[1]/preceding::button[2]</value>
      <webElementGuid>0d2ac48e-a6b7-433e-9c5d-66e8e86543c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sub Category']/parent::*</value>
      <webElementGuid>cbd95e01-05ef-423f-9d41-5999b75d0349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>71765cd3-6364-4eec-8c2c-e1260266c7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-tabs-tab-:Riqllllaqla:' and @type = 'button' and (text() = 'Sub Category' or . = 'Sub Category')]</value>
      <webElementGuid>964f4579-03f5-4c0c-b8eb-c8d8f8a1f434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
