<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CategoryAllWatersTT555Categories2Ben285_7d2483</name>
   <tag></tag>
   <elementGuidId>e7eb3023-cdd2-4d0e-a5f7-0fa0e7418e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34f64fd9-cecf-4e32-b55d-8e92a31acf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid p-4 items-center sm:grid-cols-auto md:grid-cols-2 </value>
      <webElementGuid>5d0577bd-9fe7-4623-b31b-53598f4879c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category:AllWatersTT555Categories2Ben285PizzaKFCSSS</value>
      <webElementGuid>9b91fa72-aff3-43fb-9e79-453fe8eb672c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r3:&quot;)/div[@class=&quot;mt-6 overflow-x-auto lg:overflow-x-hidden bg-white text-gray-700 w-auto h-auto shadow-lg overflow-hidden dark:bg-slate-700 rounded-2xl&quot;]/div[@class=&quot;grid p-4 items-center sm:grid-cols-auto md:grid-cols-2&quot;]</value>
      <webElementGuid>5b98143c-78b6-47e6-b5f6-68f5906b039b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div</value>
      <webElementGuid>d79ff9d2-d0a1-4579-96f8-95d3edcf404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add SubCategory'])[1]/following::div[4]</value>
      <webElementGuid>49878997-07f2-4968-a8da-a6c92c40f6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Category'])[1]/following::div[6]</value>
      <webElementGuid>93a63e33-002a-4870-856c-0ad938edf45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUB CATEGORY'])[1]/preceding::div[4]</value>
      <webElementGuid>5ca56866-bd49-419e-a569-c3cf508351a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div/div</value>
      <webElementGuid>f36cb164-3bff-46fd-8cf1-30b4ad79ced9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Category:AllWatersTT555Categories2Ben285PizzaKFCSSS' or . = 'Category:AllWatersTT555Categories2Ben285PizzaKFCSSS')]</value>
      <webElementGuid>aad1c7d8-fde7-4885-a9bd-92e64610244a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
