<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Supplier CodeSupplier NameGroup Supplie_2214d4</name>
   <tag></tag>
   <elementGuidId>50627c1c-dfab-4f89-9b1f-ec5eb3bc7c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:r3:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4a04508-10b5-4884-86d2-eb9840120aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-panel-:r3:</value>
      <webElementGuid>a99ffe98-413d-43a5-92eb-6bdf07882b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tabpanel</value>
      <webElementGuid>b0a35f63-f9df-40b2-9534-34b245e1f3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>431d7fc8-da32-45c3-a0c6-d895d410619f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>01e7d5f9-f877-4ace-877d-472565aa1205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:r0:</value>
      <webElementGuid>77e5605d-1021-49af-9612-993f0a60b724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supplier CodeSupplier NameGroup SupplierCreditVatVat IncludeItem Number a4toeychathai87%Yes0Show:102550100/1 Items1</value>
      <webElementGuid>40f8e880-1047-45c3-8a51-364ee668832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r3:&quot;)</value>
      <webElementGuid>e09f6f47-01a4-4746-a57a-a63f98667c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r3:']</value>
      <webElementGuid>e18b0d95-e248-45d8-a9f9-9542aa6a72e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Supplier'])[1]/following::div[3]</value>
      <webElementGuid>b5ff1e5b-62b9-46d8-a529-2e41f0d199f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Supplier'])[1]/following::div[4]</value>
      <webElementGuid>c16a4ab8-c9b6-46ce-9e88-2b4924523ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[3]/div</value>
      <webElementGuid>199e6e04-d8b5-4d04-be3c-59ddbabff28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-tabs-panel-:r3:' and (text() = 'Supplier CodeSupplier NameGroup SupplierCreditVatVat IncludeItem Number a4toeychathai87%Yes0Show:102550100/1 Items1' or . = 'Supplier CodeSupplier NameGroup SupplierCreditVatVat IncludeItem Number a4toeychathai87%Yes0Show:102550100/1 Items1')]</value>
      <webElementGuid>9a17c4dd-f5f5-40a6-b6f9-4fe398bc6c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
