<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Category_flex flex-initial justify-_a9ff94</name>
   <tag></tag>
   <elementGuidId>d14d2b6f-6656-435d-9539-d90c5a9665ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.justify-between.bg-white.p-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d28403a9-acec-4b54-b194-ea34db9274a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between bg-white p-4</value>
      <webElementGuid>947f2b44-208f-4c9b-a4f8-d1e58c219d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r3:&quot;)/div[@class=&quot;mx-6 bg-white text-gray-700 w-auto h-auto mt-4 shadow-lg overflow-x-auto dark:bg-slate-700 rounded-xl&quot;]/div[@class=&quot;flex items-center justify-between bg-white p-4&quot;]</value>
      <webElementGuid>650e665c-1d2c-40c7-a9c6-ee6e09628b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div</value>
      <webElementGuid>7c794ed4-f42c-4c41-9bf0-4ba609cdfcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Supplier'])[1]/following::div[5]</value>
      <webElementGuid>f5a0852a-0183-4d95-b46c-5d0265437b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Supplier'])[1]/following::div[6]</value>
      <webElementGuid>891d852b-e78e-4d9f-beae-065e3d43a19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Code'])[1]/preceding::div[2]</value>
      <webElementGuid>5a52102b-cc0a-4a77-845c-449f42fe9ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Name'])[1]/preceding::div[2]</value>
      <webElementGuid>e902348b-f2e9-49c7-84ab-a4b7ce4bda86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>d267df16-1e41-4350-a376-cfa69d65b0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:R3qllllaqla:']/div/div/div</value>
      <webElementGuid>77f68759-6d09-4668-96e8-f75f4cb9b722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Category'])[1]/following::div[5]</value>
      <webElementGuid>f0b85585-7728-48df-82cd-00bbefe7a687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Category'])[1]/following::div[7]</value>
      <webElementGuid>9b1e1dac-61aa-4409-a52f-5aed5327f250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORY'])[1]/preceding::div[1]</value>
      <webElementGuid>2d72daa9-1374-4444-af74-570e7fcf33af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUB CATEGORY'])[1]/preceding::div[1]</value>
      <webElementGuid>093199e7-1e73-4f54-bbc1-868313400f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>8f503411-9283-4367-b782-2633acb4e154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
