<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Category_input-group-1</name>
   <tag></tag>
   <elementGuidId>a9e0baaa-18ae-49ed-82e8-ee9bae7a1686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-group-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-group-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe5d6875-2741-409a-a9a5-fcc31b679806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-group-1</value>
      <webElementGuid>b85b14f7-26b4-4d2e-ab4b-9aff3a85882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 border border-gray-300 text-gray-900 text-[14px] rounded-[10px] focus:outline-orange-200 block pl-10 py-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white</value>
      <webElementGuid>d85b20d7-0928-4178-8ec9-d9b8073d69d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>4a281d6f-d4b7-4cb5-a5d1-64467f33a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d24e6bdb-000f-4293-a9b7-42b09b57604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-group-1&quot;)</value>
      <webElementGuid>ab8352fc-e02f-4453-95ce-150a9656bf4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-group-1']</value>
      <webElementGuid>a0a83e59-a8a1-4c02-98ae-0ced9c40a621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:R6alllaqla:']/div/div/div/input</value>
      <webElementGuid>b4720051-eef2-4d2f-bb46-037a85670775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7a95b194-b030-49e8-b8cf-b2efad311c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-group-1' and @placeholder = 'Search...' and @type = 'text']</value>
      <webElementGuid>4a9d7ee7-cb15-48c6-97b5-5014721aeafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div/div/input</value>
      <webElementGuid>adc98b62-592e-4fd9-b017-66791a89abbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r2:']/div/div/div/input</value>
      <webElementGuid>66758c5c-1f00-4b6f-9f58-665934805e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:R3qllllaqla:']/div/div/div/input</value>
      <webElementGuid>d452eef1-5bb6-4a86-9e4d-425e03f38f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
