<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Company Name</name>
   <tag></tag>
   <elementGuidId>e098bbe9-2b86-4814-aee5-6401b84e4e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-:r7:']/div[4]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4b0d7dd2-a9f8-406e-ac25-8aa98ff295f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-[#495057] pb-2</value>
      <webElementGuid>e22cf796-371c-4f43-884b-9f1e7f6e8e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Name  *</value>
      <webElementGuid>24ccdace-c0bf-4f8d-921b-2aecb77f4f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:r7:&quot;)/div[@class=&quot;grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2&quot;]/div[@class=&quot;p-4&quot;]/label[@class=&quot;block text-[#495057] pb-2&quot;]</value>
      <webElementGuid>257f8184-b19b-4e87-ae1e-27505cbe9fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r7:']/div[4]/div/label</value>
      <webElementGuid>6cfa7f70-8a76-4506-8687-113bd3f71afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax ID'])[1]/following::label[1]</value>
      <webElementGuid>06adbb24-046f-4307-894a-c9baadc48b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[2]</value>
      <webElementGuid>e2f00ff2-144f-4e9e-b29b-996434c8477b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vat'])[2]/preceding::label[1]</value>
      <webElementGuid>ee0f2923-2a38-48c6-8437-8502c40fbfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>03917f7d-a9ca-440b-bf4d-1c7a93171348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Company Name  *' or . = 'Company Name  *')]</value>
      <webElementGuid>c8172b5e-505c-4648-aa3e-887cd10ff8d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
