<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllWatersTT555Categories2Ben285PizzaKFCSSS</name>
   <tag></tag>
   <elementGuidId>33b5d948-5123-487d-9f16-64330b76cc54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c0666c21-9037-45e8-8bfa-d421eb403394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 border w-4/5 mr-4 border-gray-300  text-[#92929D] text-sm py-2 pl-2 pr-8  rounded-lg focus:ring-cream-1000  focus:border-cream-1000 dark:bg-gray-700 dark:border-gray-600  dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500  dark:focus:border-blue-500 </value>
      <webElementGuid>2fb48dd6-361d-42a8-b07b-649b52951c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllWatersTT555Categories2Ben285PizzaKFCSSS</value>
      <webElementGuid>f17855c6-0aef-445f-98f9-e76cda473b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r3:&quot;)/div[@class=&quot;mt-6 overflow-x-auto lg:overflow-x-hidden bg-white text-gray-700 w-auto h-auto shadow-lg overflow-hidden dark:bg-slate-700 rounded-2xl&quot;]/div[@class=&quot;grid p-4 items-center sm:grid-cols-auto md:grid-cols-2&quot;]/div[@class=&quot;md:grid md:grid-cols-1 md:justify-items-end text-[#92929D] w-full m-2 relative items-center&quot;]/div[@class=&quot;flex items-center&quot;]/select[@class=&quot;bg-gray-50 border w-4/5 mr-4 border-gray-300  text-[#92929D] text-sm py-2 pl-2 pr-8  rounded-lg focus:ring-cream-1000  focus:border-cream-1000 dark:bg-gray-700 dark:border-gray-600  dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500  dark:focus:border-blue-500&quot;]</value>
      <webElementGuid>25328535-e714-4e5a-8c0c-36fb1545f20f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r3:']/div/div/div[2]/div/select</value>
      <webElementGuid>5855d4b4-920c-4201-ab3d-59a7d3935b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category:'])[1]/following::select[1]</value>
      <webElementGuid>218280d2-ee76-4c7b-aed2-5c120b93eb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add SubCategory'])[1]/following::select[1]</value>
      <webElementGuid>a46a97dd-ecf5-40dd-a949-b680f996fd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUB CATEGORY'])[1]/preceding::select[1]</value>
      <webElementGuid>e1aedfcd-9e4d-4e43-9d18-56aa2c8656b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORY'])[1]/preceding::select[1]</value>
      <webElementGuid>20347417-055b-40f6-8fd3-ab8087d71210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2097704a-072b-4ce2-9464-b006d64a9b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'AllWatersTT555Categories2Ben285PizzaKFCSSS' or . = 'AllWatersTT555Categories2Ben285PizzaKFCSSS')]</value>
      <webElementGuid>39eb098e-e47e-4f49-ac66-84273e144b05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
