<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0001</name>
   <tag></tag>
   <elementGuidId>3636b78f-d6ca-470a-8378-d00f9e6dfec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-panel-:R6alllaqla:']/div/div[2]/div/table/tbody/tr[8]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>393dd7b4-0cb1-49b2-aa94-afa084a4a310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 w-[140px]  text-[#0D998B]</value>
      <webElementGuid>012ae058-82d4-460f-bb2e-0f260833ee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 0001</value>
      <webElementGuid>9994b420-418b-422e-93b2-53f27792324c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:R6alllaqla:&quot;)/div[@class=&quot;mx-6 bg-white text-gray-700 w-auto h-auto mt-4 shadow-lg  dark:bg-slate-700 rounded-xl&quot;]/div[@class=&quot;px-6&quot;]/div[@class=&quot;rounded-xl space-x-8&quot;]/table[@class=&quot;table-auto w-full text-xs text-gray-500 whitespace-nowrap dark:text-gray-400 mr-10 md:mr-0&quot;]/tbody[1]/tr[@class=&quot;bg-white dark:bg-gray-600 px-6 bg-white dark:bg-gray-600 dark:border-gray-700&quot;]/td[@class=&quot;px-6 w-[140px]  text-[#0D998B]&quot;]</value>
      <webElementGuid>810dca25-7560-493d-ac02-a48dea85cc7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:R6alllaqla:']/div/div[2]/div/table/tbody/tr[8]/td</value>
      <webElementGuid>f05f0964-bd9a-4b8d-b9e6-0909ee63b479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[6]/following::td[3]</value>
      <webElementGuid>96466afe-57eb-4ef2-b67d-5f5ea5907f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tee noi'])[2]/following::td[6]</value>
      <webElementGuid>4c4c20c8-4c43-4e90-a54d-257adceb7950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nattha sukaum'])[1]/preceding::td[1]</value>
      <webElementGuid>e6f1018b-0a8a-4666-98fc-acc7f82f5964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chathai'])[3]/preceding::td[2]</value>
      <webElementGuid>437cdbfb-8b30-44e5-b636-ec44ec951273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td</value>
      <webElementGuid>2769a425-52ca-41ef-a2e7-1602214e6bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' 0001' or . = ' 0001')]</value>
      <webElementGuid>cfe3a1d7-1bab-4348-9bbc-59653fa5ec57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
