<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>4733124a-4d62-414e-9dde-22301c95ba18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-username-for-credentials-provider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-username-for-credentials-provider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f986ca6-bd03-4624-ab9a-37504da5362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>a68f06ca-4aa7-4488-8174-ec55ce0a44d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-username-for-credentials-provider</value>
      <webElementGuid>d6c53c58-57f1-4727-ac48-00f669d1a301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>918c393d-ef1a-40dc-866a-0a3ca12ca6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>jsmith</value>
      <webElementGuid>a268cb73-d540-483b-a86d-0866e2f0dd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>9f477b01-cf09-4094-a33b-ead5b64cf392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-username-for-credentials-provider&quot;)</value>
      <webElementGuid>a9041598-d16c-42e0-8ad8-8786fa6aa31b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-username-for-credentials-provider']</value>
      <webElementGuid>7fae2ed0-4d8b-4d5b-8a4d-bee1cd59d3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>907f6c64-ffb4-4492-a486-2fe08002bd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'input-username-for-credentials-provider' and @type = 'text' and @placeholder = 'jsmith']</value>
      <webElementGuid>dfb4497d-cc76-4e98-a35d-701e00c0087c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
