<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New Test Object</name>
   <tag></tag>
   <elementGuidId>ebf20821-0312-455b-8b7f-5b2b6ae59c13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-make-appointment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>not equal</matchCondition>
      <name>fdsfsdf</name>
      <type>Main</type>
      <value>sdfsdf</value>
      <webElementGuid>fd22bca4-e1ef-428b-bc9e-409fd230ad36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>dsfsdf</value>
      <webElementGuid>0a571d31-5428-45b6-9ca8-9b5e48a932ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>fd0c33b0-17b9-4984-9740-1642bb4f75f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
